import { ReactNode } from 'react';
import './globals.css';
import localFont from 'next/font/local';
import Nav from '@/components/Nav/Nav';

const madimiFont = localFont({
  src: '../public/fonts/MadimiOne-Regular.ttf',
  display: 'swap',
  variable: '--font-madimi',
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html suppressHydrationWarning className={`${madimiFont.variable}`}>
      <body className='h-screen'>
        <div className='container m-auto pt-4'>{children}</div>
      </body>
    </html>
  );
}
